name: ob_dump_reader
description: "Minimal ObjectBox LMDB reader toolkit"
version: 0.1.0-beta.1
homepage: https://github.com/o-murphy/ob-dump
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  ffi: ^2.1.4
  flat_buffers: ^25.9.23
  path: ^1.9.1
dev_dependencies:
  test: ^1.25.0

executables:
  build: build
