#ifndef OB_DUMP_INTERNAL_SCHEMA_JSON_HPP
#define OB_DUMP_INTERNAL_SCHEMA_JSON_HPP

#include <string>

namespace ob_dump_internal {

// Re-serializes a parsed Schema as a clean, minimal JSON document — just
// what decodeObject() actually uses, without ObjectBox's model.json noise
// (uid strings, indexes, retired-property arrays, flags):
//
//   { "entities": [
//       { "entityId": 1, "name": "Ammo",
//         "properties": [
//           { "id": 1, "name": "bcG1", "type": "Double", "vtableSlot": 4 },
//           ...
//         ]
//       },
//       ...
//   ] }
//
// Useful on its own for inspecting what this library understood from a
// model.json, and as the companion lookup (entityId -> table name/shape)
// needed by anyone consuming the .fbs generated by generateFbs() — the
// .fbs's flatc-generated code can decode a table's bytes once you already
// know which table type they are; this is how you know that, and how you
// derive the LMDB key's entity_id -> that mapping (see docs/BACKLOG.md).
//
// Throws std::runtime_error on the same conditions Schema::parse() does.
std::string schemaToJson(const std::string& modelJson);

}  // namespace ob_dump_internal

#endif  // OB_DUMP_INTERNAL_SCHEMA_JSON_HPP
