#include "internal/fbs_gen.hpp"

#include <map>
#include <sstream>

#include "internal/schema.hpp"

namespace ob_dump_internal {

namespace {

// FlatBuffers .fbs field-type keyword for each PropertyType. Vector types
// get the same element keyword wrapped in `[...]`.
const char* fbsTypeName(PropertyType type) {
    switch (type) {
        case PropertyType::Bool:
        case PropertyType::BoolVector:     return "bool";
        case PropertyType::Byte:
        case PropertyType::ByteVector:     return "byte";
        case PropertyType::Short:
        case PropertyType::ShortVector:    return "short";
        // Char is a 16-bit code unit, unsigned by convention (see
        // PropertyType::Char doc comment) — .fbs has no native "char".
        case PropertyType::Char:
        case PropertyType::CharVector:     return "ushort";
        case PropertyType::Int:
        case PropertyType::IntVector:      return "int";
        case PropertyType::Long:
        case PropertyType::LongVector:
        case PropertyType::Date:
        case PropertyType::DateVector:
        case PropertyType::Relation:
        case PropertyType::DateNano:
        case PropertyType::DateNanoVector: return "long";
        case PropertyType::Float:
        case PropertyType::FloatVector:    return "float";
        case PropertyType::Double:
        case PropertyType::DoubleVector:   return "double";
        case PropertyType::String:
        case PropertyType::StringVector:   return "string";
        case PropertyType::Flex:           return "ubyte";  // raw, still-encoded bytes
        case PropertyType::Unknown:        return "ubyte";  // shape genuinely unknown
    }
    return "ubyte";
}

bool isVectorType(PropertyType type) {
    switch (type) {
        case PropertyType::BoolVector:
        case PropertyType::ByteVector:
        case PropertyType::ShortVector:
        case PropertyType::CharVector:
        case PropertyType::IntVector:
        case PropertyType::LongVector:
        case PropertyType::FloatVector:
        case PropertyType::DoubleVector:
        case PropertyType::StringVector:
        case PropertyType::DateVector:
        case PropertyType::DateNanoVector:
            return true;
        default:
            return false;
    }
}

void writeField(std::ostringstream& out, const PropertyDef& prop) {
    out << "  " << prop.name << ":";
    if (prop.type == PropertyType::Flex) {
        out << "[ubyte];  // Flex: raw FlexBuffers-encoded bytes, not decoded further here\n";
        return;
    }
    const char* base = fbsTypeName(prop.type);
    if (isVectorType(prop.type)) {
        out << "[" << base << "]";
    } else {
        out << base;
    }
    if (prop.type == PropertyType::Unknown) {
        out << " (deprecated);  // unrecognized PropertyType code, shape unknown\n";
    } else {
        out << ";\n";
    }
}

void writeReservedPlaceholder(std::ostringstream& out, int propertyId) {
    // Retired property: model.json keeps its uid (in retiredPropertyUids)
    // but not its original type, so any scalar type works here — flatc
    // never generates an accessor for a deprecated field regardless.
    out << "  _reserved_" << propertyId << ":ubyte (deprecated);\n";
}

}  // namespace

std::string generateFbs(const std::string& modelJson) {
    Schema schema = Schema::parse(modelJson);

    std::ostringstream out;
    out << "// Auto-generated by `ob_dump --fbs` from objectbox-model.json. Do not edit by hand.\n";
    out << "// Field order matches ObjectBox property id order (determines each field's vtable\n";
    out << "// slot); gaps from retired properties are filled with deprecated placeholders to\n";
    out << "// keep slot numbering aligned. See docs/BACKLOG.md for the full rationale — in\n";
    out << "// particular, this .fbs plus flatc only replaces the per-record FlatBuffers decode,\n";
    out << "// not LMDB access or the ObjectBox key-format parsing.\n\n";

    for (const EntityDef* entity : schema.all()) {
        std::map<int, const PropertyDef*> byId;
        int maxId = 0;
        for (const auto& prop : entity->properties) {
            byId[prop.id] = &prop;
            if (prop.id > maxId) maxId = prop.id;
        }

        out << "table " << entity->name << " {\n";
        for (int id = 1; id <= maxId; ++id) {
            auto it = byId.find(id);
            if (it == byId.end()) {
                writeReservedPlaceholder(out, id);
            } else {
                writeField(out, *it->second);
            }
        }
        out << "}\n\n";
    }

    return out.str();
}

}  // namespace ob_dump_internal
